// Sondes exploratoires : chaque épreuve affiche ce qu'elle voit, sans juger.
import { afterEach, test } from 'node:test'
import { horloge, qcm, salle, sondage } from './harnais'

let h: ReturnType<typeof horloge> | null = null
afterEach(() => {
  h?.arreter()
  h = null
})

test('sonde : une partie simple', () => {
  h = horloge()
  const s = salle([{ id: 'q', title: 'Q', questions: [qcm('Un ?'), qcm('Deux ?')] }])
  s.inscrire('Alice')
  s.inscrire('Bruno')
  s.lancer()
  s.choisir('q')
  h.avancer(3000)
  console.log('phase', s.st.phase, s.chronos())
  s.repondre('Alice', { type: 'answer', choice: 0 })
  s.repondre('Bruno', { type: 'answer', choice: 1 })
  console.log('après réponses', s.chronos())
  h.avancer(700)
  console.log('phase', s.st.phase, s.ledger.total(s.idDe('Alice')), s.ledger.total(s.idDe('Bruno')))
  s.fermer()
})

test('sonde : pause, puis Révéler', () => {
  h = horloge()
  const s = salle([{ id: 'q', title: 'Q', questions: [qcm('Un ?'), qcm('Deux ?')] }])
  s.inscrire('Alice')
  s.inscrire('Bruno')
  s.lancer()
  s.choisir('q')
  h.avancer(3000)
  s.commande({ type: 'pause' })
  s.commande({ type: 'next', ...s.visee() })
  const v = s.vueHote()!
  console.log('hôte', v.phase, 'paused=', v.paused, 'remainingMs=', v.remainingMs)
  console.log('téléphone', s.vueDe('Alice')?.phase, 'paused=', s.vueDe('Alice')?.paused)
  s.fermer()
})

test('sonde : sondage, un candidat exclu', () => {
  h = horloge()
  const s = salle([{ id: 'q', title: 'Q', questions: [sondage('Qui ?'), qcm('Deux ?')] }])
  s.inscrire('Alice')
  s.inscrire('Bruno')
  s.inscrire('Chloé')
  s.lancer()
  s.choisir('q')
  h.avancer(3000)
  console.log('avant', s.vueDe('Alice')?.answers, s.vueHote()?.answers)
  s.exclure('Chloé')
  console.log('après', s.vueDe('Alice')?.answers, s.vueHote()?.answers)
  s.fermer()
})

test('sonde : « au clic » pendant l’intertitre', () => {
  h = horloge()
  const s = salle([{ id: 'q', title: 'Q', questions: [qcm('Un ?'), qcm('Deux ?', { intertitre: 'Manche 2' })] }])
  s.inscrire('Alice')
  s.lancer({ autoNextSeconds: 10 })
  s.choisir('q')
  h.avancer(3000)
  s.repondre('Alice', { type: 'answer', choice: 0 })
  h.avancer(700)
  console.log('révélée', s.st.phase, s.chronos())
  h.avancer(10000)
  console.log('intertitre', s.st.phase, s.chronos(), 'vue hôte deadline', s.vueHote()?.deadline, 'auto', s.vueHote()?.autoNextSeconds)
  s.commande({ type: 'autoNext', seconds: null })
  console.log('au clic', s.st.phase, s.chronos(), 'vue hôte deadline', s.vueHote()?.deadline, 'auto', s.vueHote()?.autoNextSeconds)
  h.avancer(10000)
  console.log('10 s plus tard', s.st.phase)
  s.fermer()
})

test('sonde : autoNext sans secondes', () => {
  h = horloge()
  const s = salle([{ id: 'q', title: 'Q', questions: [qcm('Un ?'), qcm('Deux ?'), qcm('Trois ?')] }])
  s.inscrire('Alice')
  s.lancer()
  s.choisir('q')
  h.avancer(3000)
  s.commande({ type: 'autoNext' })
  console.log('autoNextSeconds', s.st.autoNextSeconds)
  s.repondre('Alice', { type: 'answer', choice: 0 })
  h.avancer(700)
  console.log('révélée', s.st.phase, s.st.qIndex, s.chronos())
  h.avancer(5)
  console.log('5 ms après', s.st.phase, s.st.qIndex)
  s.fermer()
})

test('sonde : arrivé au podium', () => {
  h = horloge()
  const s = salle([{ id: 'q', title: 'Q', questions: [qcm('Un ?'), qcm('Deux ?')] }])
  s.inscrire('Zoé')
  s.inscrire('Yves')
  s.inscrire('Xavier')
  s.lancer()
  s.choisir('q')
  h.avancer(3000)
  s.repondre('Zoé', { type: 'answer', choice: 0 })
  s.repondre('Yves', { type: 'answer', choice: 1 })
  s.repondre('Xavier', { type: 'answer', choice: 1 })
  h.avancer(700)
  s.commande({ type: 'next', ...s.visee() })
  s.repondre('Zoé', { type: 'answer', choice: 0 })
  s.repondre('Yves', { type: 'answer', choice: 1 })
  s.repondre('Xavier', { type: 'answer', choice: 1 })
  h.avancer(700)
  s.commande({ type: 'next', ...s.visee() })
  console.log('phase', s.st.phase)
  console.log('podium avant', s.vueHote()?.standings?.map((r: any) => `${r.name}:${r.points}:${r.rank}`))
  s.rejoindre('Aaron')
  console.log('podium après', s.vueHote()?.standings?.map((r: any) => `${r.name}:${r.points}:${r.rank}`))
  console.log('téléphone d’Aaron', JSON.stringify({ podium: s.vueDe('Aaron')?.podium?.map((r: any) => r.name), idx: s.vueDe('Aaron')?.yourPodiumIndex, rank: s.vueDe('Aaron')?.yourQuizRank }))
  console.log('téléphone de Xavier', JSON.stringify({ podium: s.vueDe('Xavier')?.podium?.map((r: any) => r.name), idx: s.vueDe('Xavier')?.yourPodiumIndex }))
  s.fermer()
})

test('sonde : deux Camille au sondage', () => {
  h = horloge()
  const s = salle([{ id: 'q', title: 'Q', questions: [sondage('Qui ?')] }])
  s.inscrire('Camille', '🦊')
  s.inscrire('Camille', '🐼')
  s.inscrire('Hugo', '🐻')
  s.lancer()
  s.choisir('q')
  h.avancer(3000)
  console.log('liste du téléphone', JSON.stringify(s.vueDe('Hugo')?.answers))
  s.fermer()
})

test('sonde : arrivé dans le souffle', () => {
  h = horloge()
  const s = salle([{ id: 'q', title: 'Q', questions: [qcm('Un ?'), qcm('Deux ?')] }])
  s.inscrire('Alice')
  s.inscrire('Bruno')
  s.lancer()
  s.choisir('q')
  h.avancer(3000)
  s.repondre('Alice', { type: 'answer', choice: 0 })
  s.repondre('Bruno', { type: 'answer', choice: 0 })
  h.avancer(100)
  s.rejoindre('Zoé')
  console.log('chronos après arrivée', s.chronos())
  h.avancer(600)
  const v = s.vueDe('Zoé') as any
  console.log('phase', s.st.phase, 'Zoé justArrived', v.justArrived, 'yourPoints', v.yourPoints)
  console.log('journal Zoé', JSON.stringify(s.answers.all().filter(r => r.playerId === s.idDe('Zoé')).map(r => ({ q: r.qIndex, answered: r.answered, points: r.points }))))
  s.fermer()
})
